micronaut.application.name = 'electronicShopAnalytics'

[datasources.default]
url = 'jdbc:postgresql://localhost:5432/postgres'
driverClassName = 'org.postgresql.Driver'
username = 'postgres'
password = ''

[micronaut.security]
authentication = 'bearer'
token.jwt.signatures.secret.generator.secret = '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
intercept-url-map = [{ access = 'isAnonymous()', pattern = '/swagger/**' }, { access = 'isAnonymous()', pattern = '/swagger-ui/**' }]

[micronaut.router.static-resources.swagger]
paths = 'classpath:META-INF/swagger'
mapping = '/swagger/**'

[micronaut.router.static-resources.swagger-ui]
paths = 'classpath:META-INF/swagger/views/swagger-ui'
mapping = '/swagger-ui/**'
